helm repo add bitnami https://charts.bitnami.com/bitnami

helm repo update

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: mlops
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
EOF

echo -n 'admin' | base64
echo -n 'adminpassword' | base64

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-user
  namespace: mlops
data:
  root-user: YWRtaW4=
  root-password: YWRtaW5wYXNzd29yZA==
EOF

cat <<EOF > values.yaml
global:
  defaultStorageClass: "longhorn"

service:
  type: LoadBalancer
  ports:
    minio: 9000
    console: 9001

ingress:
  enabled: true
  hostname: minio.mylab.com
  servicePort: minio-console
  annotations:
    kubernetes.io/ingress.class: "nginx" 
  tls: true
  selfSigned: true

persistence:
  enabled: true
  storageClassName: "longhorn"
  size: 10Gi # Adjust based on your requirements
  accessMode: ReadWriteOnce
  existingClaim: "minio-pvc"

auth:
  existingSecret: "minio-root-user"
  rootUserSecretKey: "root-user"
  rootPasswordSecretKey: "root-password"
  forcePassword: false
  useCredentialsFiles: false
  forceNewKeys: false
  defaultBuckets: "mlflow-artifacts"
  disableWebUI: false
tls:
  enabled: true
  autoGenerated: true

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
EOF

helm upgrade --install my-release oci://registry-1.docker.io/bitnamicharts/minio -f values.yaml --namespace mlops

# helm uninstall my-release --namespace mlops

# my-release-minio.mlops.svc.cluster.local

export ROOT_USER=$(kubectl get secret --namespace mlops minio-root-user -o jsonpath="{.data.root-user}" | base64 -d)
export ROOT_PASSWORD=$(kubectl get secret --namespace mlops minio-root-user -o jsonpath="{.data.root-password}" | base64 -d)

echo "Root User: $ROOT_USER"
echo "Root Password: $ROOT_PASSWORD"

kubectl run --namespace mlops my-release-minio-client \
  --rm --tty -i --restart='Never' \
  --env MINIO_SERVER_ROOT_USER=$ROOT_USER \
  --env MINIO_SERVER_ROOT_PASSWORD=$ROOT_PASSWORD \
  --image docker.io/bitnami/minio-client:2024.11.21-debian-12-r1 -- \
  mc alias set myminio https://192.168.9.112:9000 $ROOT_USER $ROOT_PASSWORD --insecure
  
#   https://minio.mylab.com:9001/login

#   Access Key: CeGeT5fesfdHa4unYt2p

#   Secret Key:ZxxHWqpOfy8SGzkzGbjMkG86tudAq9KAiPckB5gJ



