---
- name: Prepare VMs for RKE2
  import_playbook: tasks/prepare_vm.yaml

- name: Deploy RKE2
  import_playbook: tasks/deploy_rke2.yaml
  when: RKE2_MODE == 'normal'

- name: Deploy RKE2 in HA mode
  import_playbook: tasks/deploy_rke2_ha.yaml
  when: RKE2_MODE == 'ha'

- name: Post Install
  import_playbook: tasks/post_install.yaml

- name: Install Rancher on RKE2 master
  import_playbook: tasks/install_rancher.yaml
