- name: Deploy RKE2
  hosts: k8s_cluster
  become: yes
  vars:
    rke2_version: "{{ rke2_version }}"
    rke2_cni: ["{{ rke2_cni }}"] # or [cilium]
    rke2_token: "{{ rke2_token }}"
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
  roles:
     - role: lablabs.rke2