- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_version: v1.30.6+rke2r1
    rke2_ha_mode: true
    rke2_api_ip : 192.168.9.200
    rke2_download_kubeconf: true
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
  roles:
     - role: lablabs.rke2
