- name: Deploy RKE2
  hosts: k8s_cluster
  become: yes
  vars:
    rke2_version: "{{ rke2_version }}"
    rke2_cni: ["{{ rke2_cni }}"]  # or [cilium]
    rke2_token: "{{ rke2_token }}"
    rke2_ha_mode: true
    rke2_ha_mode_kubevip: "{{ rke2_ha_mode_kubevip }}"
    rke2_ha_mode_keepalived: "{{ rke2_ha_mode_keepalived }}"
    rke2_api_ip: "{{ rke2_api_ip }}"
    rke2_download_kubeconf: true
    rke2_additional_sans: >
      {{ groups['masters'] | map('extract', hostvars, 'ansible_host') | list + [rke2_api_ip] }}
    rke2_loadbalancer_ip_range:
      range-global: "{{ rke2_loadbalancer_range }}"
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
  roles:
    - role: lablabs.rke2
