- name: Prepare VMs for RKE2
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Stop and disable UFW
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Create sysctl configuration file
      file:
        path: /etc/sysctl.d/90-rke2.conf
        state: touch

    - name: Enable IP forwarding for IPv4
      lineinfile:
        path: /etc/sysctl.d/90-rke2.conf
        line: 'net.ipv4.ip_forward=1'
        state: present

    - name: Enable IP forwarding for IPv6
      lineinfile:
        path: /etc/sysctl.d/90-rke2.conf
        line: 'net.ipv6.conf.all.forwarding=1'
        state: present

    - name: Apply sysctl settings
      command: sysctl --system
      changed_when: false

    - name: Disable swap
      command: swapoff -a
      ignore_errors: yes
      changed_when: false

    - name: Comment out swap in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)'
        line: '# \1'
        state: present

    - name: Update package lists
      block:
        - name: Run apt update
          apt:
            update_cache: yes
          register: update_result
          retries: 3
          delay: 10
          until: update_result is successful
      rescue:
        - name: Reboot and retry apt update
          reboot:
            msg: "Rebooting to retry apt update"
          register: reboot_result
        - name: Retry apt update after reboot
          apt:
            update_cache: yes
          retries: 3
          delay: 10
          until: update_result is successful

    - name: Install nfs-common
      block:
        - name: Run apt install nfs-common
          apt:
            name: nfs-common
            state: present
          register: install_nfs_result
          retries: 3
          delay: 10
          until: install_nfs_result is successful
      rescue:
        - name: Reboot and retry apt install nfs-common
          reboot:
            msg: "Rebooting to retry apt install nfs-common"
          register: reboot_result
        - name: Retry apt install nfs-common after reboot
          apt:
            name: nfs-common
            state: present
          retries: 3
          delay: 10
          until: install_nfs_result is successful

    - name: Upgrade packages
      block:
        - name: Run apt upgrade
          apt:
            upgrade: dist
            state: latest
          register: upgrade_result
          retries: 3
          delay: 10
          until: upgrade_result is successful
      rescue:
        - name: Reboot and retry apt upgrade
          reboot:
            msg: "Rebooting to retry apt upgrade"
          register: reboot_result
        - name: Retry apt upgrade after reboot
          apt:
            upgrade: dist
            state: latest
          retries: 3
          delay: 10
          until: upgrade_result is successful

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Add API IP with hostname lb to /etc/hosts (only in HA mode)
      lineinfile:
        path: /etc/hosts
        line: "{{ api_ip }} lb"
        create: yes
      when: api_ip is defined

    - name: Update /etc/hosts file with Ansible inventory in IPv4 section
      blockinfile:
        path: /etc/hosts
        marker: "# Added by Ansible - IPv4 Section"
        block: |
          {% for item in groups['all'] %}
          {{ hostvars[item].ansible_host }} {{ item }}
          {% endfor %}
        state: present
      when: ansible_host is defined

    - name: Set hostname based on inventory_hostname
      hostname:
        name: "{{ inventory_hostname }}"
      when: inventory_hostname in groups['masters'] + groups['workers']

    - name: Install open-iscsi
      block:
        - name: Run apt install open-iscsi
          apt:
            name: open-iscsi
            state: present
          register: install_iscsi_result
          retries: 3
          delay: 10
          until: install_iscsi_result is successful
      rescue:
        - name: Reboot and retry apt install open-iscsi
          reboot:
            msg: "Rebooting to retry apt install open-iscsi"
          register: reboot_result
        - name: Retry apt install open-iscsi after reboot
          apt:
            name: open-iscsi
            state: present
          retries: 3
          delay: 10
          until: install_iscsi_result is successful

    - name: Reboot the server to apply changes
      reboot:
        msg: "Rebooting to apply changes"
        connect_timeout: 5
      when: inventory_hostname in groups['masters'] + groups['workers']
